# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='my_post',
        ),
    ]
